#!/bin/sh
if [ -f /Ultimate/skin.xml ]; then
  rm -rf /usr/share/enigma2/Ultimate/
  mv /tmp/Ultimate /usr/share/enigma2/
fi
echo "                                                          "
echo " ..Ultimate HD Skin  by stein17 successful installed. "
echo "                                                          "
exit 0

