#!/bin/sh
echo "                                                          "
echo " ...Poster-PLi-HD-FullNight-Mod-stein17 successful installed.  "
echo "                                                          "
exit 0


