#!/bin/sh
echo "                                                          "
echo " ...GradientFHD Skin  by stein17 successful installed.  "
echo "                                                          "
exit 0
