#!/bin/sh
echo "                                                          "
echo " ...BlueAccents-FHD Skin  by stein17 successful installed.  "
echo "                                                          "
exit 0
