#!/bin/sh
echo "                                                           "
echo " BootlogoSwitcher plugin removed...    									 "
echo "                                                           "
