#!/bin/sh
echo "                                                          "
echo " ...Anadol Skin Full HD by stein17 successful installed.  "
echo "                                                          "
exit 0
