#!/bin/sh
rm -rf /usr/share/enigma2/Anadol
rm -rf /usr/lib/enigma2/python/Components/Converter/AND*
rm -rf /usr/lib/enigma2/python/Components/Renderer/AND*
echo "                                                          "
echo "              ...Skin successful removed.                 "
echo "                                                          "
