#!/bin/sh                                                       
rm -rf /usr/share/enigma2/Anadol
rm -rf /usr/lib/enigma2/python/Components/Converter/AND
rm -rf /usr/lib/enigma2/python/Components/Renderer/AND
echo "aktualisiere Updatequellen... "opkg update 
echo "                                                                           "
echo "                                                                           "
echo "                                                                           "
echo "                                                                           "
echo "                                                                           "
echo "                                                                           "
echo "                                                                           "
echo "  Anadol Skin Full HD by stein17 is now being installed...                 "
echo "                                                                           " 
echo "                                                                           "
echo "                                                                           "
exit 0
