#!/bin/sh
echo "                                                           "
echo " Anadol Skin Full HD by stein17 is now being removed...    "
echo "                                                           "
