#!/bin/sh
rm -rf /usr/share/enigma2/GradientFHD
rm -rf /usr/lib/enigma2/python/Components/Converter/Gradient*
rm -rf /usr/lib/enigma2/python/Components/Renderer/Gradient*
rm -rf /usr/lib/enigma2/python/Plugins/Extensions/GradientFHD*
echo "                                                                 "
echo "GradientFHD skin was successfully removed from your receiver"
echo "                                                                 "
echo "The GUI of your receiver is now rebooting....                    "
exit 0
