#!/bin/sh
if [ -f /Steampunk/skin.xml ]; then
  rm -rf /usr/share/enigma2/Steampunk/
  mv /tmp/Steampunk /usr/share/enigma2/
  rm -rf /usr/lib/enigma2/python/Plugins/Extensions/SteampunkHD/
  mv /tmp/SteampunkHD /Extensions/Plugins/python/enigma2/lib/usr/
fi
echo "                                                          "
echo " ..Steampunk Skin  by stein17 successful installed. "
echo "                                                          "
exit 0

