#!/bin/sh
rm -rf /usr/share/enigma2/Steampunk
rm -rf /usr/lib/enigma2/python/Components/Converter/Steampunk*
rm -rf /usr/lib/enigma2/python/Components/Renderer/Steampunk*
rm -rf /usr/lib/enigma2/python/Plugins/Extensions/SteampunkHD*
echo "                                                                 "
echo "Steampunk skin was successfully removed from your receiver"
echo "                                                                 "
echo "The GUI of your receiver is now rebooting....                    "
exit 0
