#!/bin/sh
rm -rf /usr/share/enigma2/Blue-Line-OE-4ATV
rm -rf /usr/lib/enigma2/python/Components/Converter/BL*
rm -rf /usr/lib/enigma2/python/Components/Renderer/BL*
echo "                                                          "
echo " ....Skin removed! You should restart GUI now!                 "
echo "    
