#!/bin/sh
echo "                                                          "
echo " ...Blue-Line-OE-4ATV by stein17 successful installed.  "
echo "                                                          "
exit 0

