#!/bin/sh                                                       
rm -rf /usr/share/enigma2/Blue-Line-OE-4ATV
rm -rf /usr/lib/enigma2/python/Components/Converter/BL
rm -rf /usr/lib/enigma2/python/Components/Renderer/BL
echo "aktualisiere Updatequellen... "opkg update 
echo "                                                                           "
echo "                                                                           "
echo "                                                                           "
echo "                                                                           "
echo "                                                                           "
echo "                                                                           "
echo "                                                                           "
echo "  Blue-Line-OE-4ATV by stein17 is now being installed...                 "
echo "                                                                           " 
echo "                                                                           "
echo "                                                                           "
exit 0

