#!/bin/sh
echo " " 
echo "***************************************************************"
echo ""                                                    
echo " BootlogoSwitcher plugin successful installed...  "
echo ""
echo "***************************************************************"   
echo " "
exit 0
